Repository SiMDE-Projects/flairsou-api, pull requests merged in 2022-04, with the labels that each got.

#145 Fixed CI tag creation bug
  .github/workflows/release.yml
  .pre-commit-config.yaml
  flairsou_frontend/src/components/pages/logout/Logout.jsx
Labels: bug

#144 fix: correction du bug du montant de la transaction
  flairsou_frontend/src/components/UI/atoms/Transaction/Operation/Operation.jsx
  flairsou_frontend/src/components/UI/atoms/Transaction/Transaction.jsx
  flairsou_frontend/src/components/UI/molecules/AccountList/AccountList.jsx
  flairsou_frontend/src/components/UI/organisms/AccountContent/AccountContent.jsx
  flairsou_frontend/src/utils/currencyFormat.js
  flairsou_frontend/src/utils/currencyFormat.test.js
Labels: bug, frontend

#147 Affichage des opérations associées aux transactions dans l'interface …
  flairsou_api/admin.py
Labels: backend

#146 Intégration de la version dans l'affichage front
  flairsou_frontend/src/components/UI/molecules/Footer/Footer.jsx
  flairsou_frontend/webpack.config.js
Labels: frontend

#149 Feat/affichage clubs front
  flairsou_frontend/src/components/App.jsx
  flairsou_frontend/src/components/UI/atoms/Transaction/Operation/Operation.jsx
  flairsou_frontend/src/components/UI/atoms/Transaction/Transaction.jsx
  flairsou_frontend/src/components/UI/molecules/Navbar/Navbar.jsx
  flairsou_frontend/src/components/UI/molecules/TransactionList/TransactionList.jsx
  flairsou_frontend/src/components/UI/organisms/AccountContent/AccountContent.jsx
  flairsou_frontend/src/components/UI/organisms/BookContent/BookContent.jsx
  flairsou_frontend/src/components/pages/account/Account.jsx
Labels: enhancement, frontend

#150 Fix/update sync assos
  proxy_pda/admin.py
  proxy_pda/utils/sync_assos.py
Labels: bug, backend

#153 fix: erreur dans l'interface de rapprochement
  flairsou_api/serializers/reconciliation_serializers.py
  flairsou_frontend/src/components/UI/atoms/Reconciliation/Reconciliation.jsx
Labels: bug, backend
