Repository SiMDE-Projects/flairsou-api, pull requests merged in 2022-02, with the labels that each got.

#83 Feature/delete useless api
  flairsou_api/tests/book.py
  flairsou_api/urls.py
  flairsou_api/views/__init__.py
  flairsou_api/views/book_views.py
  flairsou_api/views/transaction_views.py
Labels: backend

#85 Vérifie que le rôle de tréso a été validé pour autorisé l'accès
  proxy_pda/utils/retrieve_user_info.py
Labels: backend

#82 Feature/check authorization api
  flairsou_api/models/account.py
  flairsou_api/models/book.py
  flairsou_api/models/operation.py
  flairsou_api/models/transaction.py
  flairsou_api/serializers/account_serializer.py
  flairsou_api/serializers/reconciliation_serializers.py
  flairsou_api/serializers/transaction_serializers.py
  flairsou_api/tests/__init__.py
  flairsou_api/tests/account.py
  flairsou_api/tests/book.py
  flairsou_api/tests/check_access_API.py
  flairsou_api/tests/reconciliation.py
  flairsou_api/tests/transaction.py
  flairsou_api/urls.py
  flairsou_api/utils/__init__.py
  flairsou_api/utils/check_user_allowed.py
  flairsou_api/views/__init__.py
  flairsou_api/views/account_views.py
  flairsou_api/views/book_views.py
  flairsou_api/views/reconciliation_views.py
  flairsou_api/views/transaction_views.py
Labels: backend

#88 Ajout du nom de l'utilisateur dans le header
  flairsou_frontend/src/components/UI/molecules/Header/Header.jsx
  flairsou_frontend/src/components/UI/molecules/Header/header.css
  flairsou_frontend/src/components/UI/organisms/ContentWrapper/ContentWrapper.jsx
  flairsou_frontend/src/components/pages/home/Home.jsx
Labels: frontend

#96 Feature/api return account with transactions
  flairsou_api/models/operation.py
  flairsou_api/serializers/__init__.py
  flairsou_api/serializers/account_ops_serializer.py
  flairsou_api/serializers/account_serializer.py
  flairsou_api/serializers/transaction_serializers.py
  flairsou_api/tests/check_access_API.py
  flairsou_api/urls.py
  flairsou_api/views/__init__.py
  flairsou_api/views/account_views.py
Labels: backend

#98 Ajout de la vérification de l'utilisateur sur l'objet Reconciliation
  flairsou_api/models/reconciliation.py
Labels: backend

#99 Vérification de la date avec <=
  flairsou_api/models/transaction.py
Labels: backend

#102 Feature/delete transaction
  flairsou_frontend/src/components/UI/atoms/Transaction/ConfirmDeleteOperation.jsx
  flairsou_frontend/src/components/UI/atoms/Transaction/Transaction.jsx
  flairsou_frontend/src/components/UI/molecules/TransactionList/TransactionList.jsx
  flairsou_frontend/src/components/UI/organisms/AccountContent/AccountContent.jsx
Labels: frontend

#103 Fix/new UI test lint
  flairsou_api/models/account.py
  flairsou_api/models/book.py
  flairsou_api/models/operation.py
  flairsou_api/models/reconciliation.py
  flairsou_api/models/transaction.py
  flairsou_api/utils/check_user_allowed.py
  flairsou_frontend/src/components/App.jsx
Labels: frontend, backend

#104 Feature/account reconciliation
  flairsou_api/serializers/account_serializer.py
  flairsou_frontend/src/components/UI/atoms/Reconciliation/Reconciliation.jsx
  flairsou_frontend/src/components/UI/atoms/Reconciliation/reconciliation.css
  flairsou_frontend/src/components/UI/organisms/AccountContent/AccountContent.jsx
Labels: frontend

#97 Feature/list assos
  Pipfile
  Pipfile.lock
  flairsou_frontend/.babelrc
  flairsou_frontend/package-lock.json
  flairsou_frontend/package.json
  flairsou_frontend/src/components/App.jsx
  flairsou_frontend/src/components/UI/atoms/NavAccount/NavAccount.jsx
  flairsou_frontend/src/components/UI/molecules/Header/Header.jsx
  flairsou_frontend/src/components/UI/molecules/Header/header.css
  flairsou_frontend/src/components/UI/molecules/Navbar/Navbar.jsx
  flairsou_frontend/src/components/UI/molecules/Navbar/navbar.css
  flairsou_frontend/src/components/UI/organisms/AccountContent/AccountContent.jsx
  flairsou_frontend/src/components/UI/organisms/ContentWrapper/ContentWrapper.jsx
  flairsou_frontend/src/components/contexts/contexts.jsx
  flairsou_frontend/src/components/pages/UserInfo.jsx
  flairsou_frontend/src/components/pages/account/Account.jsx
  flairsou_frontend/src/components/pages/home/Home.jsx
  proxy_pda/admin.py
  proxy_pda/tests.py
  proxy_pda/views.py
Labels: frontend

#80 Feature/create account
  Documentation/React.md
  flairsou_api/serializers/account_serializer.py
  flairsou_frontend/.eslintrc.json
  flairsou_frontend/package-lock.json
  flairsou_frontend/package.json
  flairsou_frontend/src/assets/accountTypeMapping.js
  flairsou_frontend/src/assets/crudActions.js
  flairsou_frontend/src/assets/errorLevels.js
  flairsou_frontend/src/components/App.jsx
  flairsou_frontend/src/components/UI/atoms/NavAccount/NavAccount.jsx
  flairsou_frontend/src/components/UI/atoms/SearchBar/SearchBar.jsx
  flairsou_frontend/src/components/UI/atoms/SearchBar/searchBar.css
  flairsou_frontend/src/components/UI/atoms/SearchBar/searchBar.scss
  flairsou_frontend/src/components/UI/molecules/AccountForm/AccountForm.jsx
  flairsou_frontend/src/components/UI/molecules/Navbar/Navbar.jsx
  flairsou_frontend/src/components/UI/organisms/AccountContent/AccountContent.jsx
  flairsou_frontend/src/components/UI/organisms/ContentWrapper/ContentWrapper.jsx
  flairsou_frontend/src/components/UI/organisms/HomeContent/HomeContent.jsx
  flairsou_frontend/src/components/contexts/contexts.jsx
  flairsou_frontend/src/components/pages/account/Account.jsx
  flairsou_frontend/src/components/pages/errors/Errors.jsx
  flairsou_frontend/src/components/pages/logout/Logout.jsx
  flairsou_frontend/src/shapes/accountShape/accountShape.js
  flairsou_frontend/templates/flairsou_frontend/index.html
  flairsou_frontend/webpack.config.js
Labels: frontend

#111 Fix/correction comptes base.py
  proxy_pda/utils/base_account_struct.py
  proxy_pda/utils/sync_assos.py
Labels: backend
